apiVersion: apps/v1
kind: Deployment
metadata:
  name: openeugene-marketing-deployment
  namespace: openeugene-marketing-prod
  labels:
    app: openeugene-marketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openeugene-marketing
  template:
    metadata:
      labels:
        app: openeugene-marketing
    spec:
      containers:
      - name: web-app
        image: codegold79/openeugene-marketing:1.0.0
        resources:
           limits:
              cpu: 0.25
              memory: 250Mi
           requests:
              cpu: 0.25
              memory: 250Mi
        ports:
        - containerPort: 3000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
